README.md

One Tree Planted is a non-profit organization.
You can find more information at:
https://onetreeplanted.org/pages/about-us

Add new global tree plating organization

---

README.md

Came across this repo and thought I'd add some Indian organizations to the list :)
Cheers!

Add Indian orgs to list

---

README.md

**Added**
- [Rotary International](https://www.rotary.org/)
- [Rotary India](https://www.rotaryindia.org/)
- Changed the the href case to the proper one.

feat (Added Rotary Club) + fix (href case)

---

README.md

Added Siruthuli, a tree-planting organization in India

Added Siruthuli

---

README.md

Added saytrees.org, a tree-planting organization in India

added saytrees.org

---

README.md

- Added **WeForest**
- Added **Trees For the Future**
- Added **International Tree Foundation**
- Added **SayTrees**
- Added **Siruthuli**
- Added **Regua**

Added Multiple Organizations under Global, India, and Brazil

---

README.md

Addressing issue #4 
Added some more organisations under India, and edited some for Canada as one of organisation was part of global and not only canada,so added same in global

edited India Links and Global Links

---

README.md

- added Ecosia (https://www.ecosia.org), the search engine, which plants trees

Update README.md with Ecosia from Germany

---

README.md

Added National Forest Foundation in the US

Added National Forest Foundation in the US

---

README.md

For Issue #4 - Added one org for India country

Add TreeSena org

---

README.md

I added a new organization under Germany. (Green Forest Fund) This is a PR for the 2020 Hacktoberfest.

Added organization under Germany

---

README.md

I have added one more organization from India and I have also placed it alphabetically correct order.
Kindly accept my PR.

Added Catch Foundation in India

---

README.md

The Tree for Life (TFL) Foundation has been added under the India section of the readme doc. I have ensured that the alphabetical order was maintained.

added Tree for Life (TFL) Foundation under India

---

README.md

fix: Global sorting

---

README.md

Hello 👋
I have Added a new Indian Organization called Isha Foundation and created a branch of that name and also added the Link.
Please Merge the Pull Request
Thanks!!

Added org that you can donate money to plant trees

---

README.md

Vanam India Foundation was added to the list under the India section. Alphabetical order was maintained.

Added Vanam India Foundation under India

---

README.md

Vetry is a Tirupur Based NGO whose mission is to plant more than 2 Lakhs tress by this year.
Thank you for reading my Pull Request

Added Vetry to ReadMe

---

README.md

fixed india alphabetical order

---

README.md

Also check if repo is excluded

Remove regua broken img

---

README.md

hello, I just add EdenProjectsIndonesia organization, please kindly check, thank you.

Add EdenProjectsIndonesia Organization

---

README.md

Added Rwanda to the list of **plant-a-tree**

Update README: Add Rwanda to the list

---

README.md

Add new section for country of Lithuania
Add the pasodinkmedi.lt organization

add lithuania

---

README.md

Under UK:
- Added **Trees for Cities**
- Added **Woodland Trust**
- Added **The National Forest**

Add more organisations in the UK

---

README.md

Added haribon org for philippines

Added Philippines

---

README.md

add Eden Projects

---

README.md

Add plant a pine tree is an easy way to help Florida State Parks get greener

Add Florida State Parks Foundation - Plant a Pine
